### PR TITLE
Correct date ranges in Agenda

### LINKED ISSUE #141: All-day events over multiple days show incorrect date range in agenda pane.
If an event covering more than one day is created with the "all day event" switch "on", then the agenda shows an incorrect date range for this event.  The last day is shown one day later than the true last day.
screenshot from 2017-09-14 11 13 51

### PR DESCRIPTION
**Pull request by Thalexander**
Handles all day events correctly when getting local datetimes from ical components

Fixes #141

### CODE REVIEW

**Comment by matzipan** [comment]
Agreed with Jeremy.

**Comment by Thalexander** [comment]
A day is only taken away from the end date, I do not believe this would be possible to handle in a sensible way in ical_to_date_time as that handles any date component.

**Comment by matzipan** [comment]
Hmm you're right, I thought this date was originating from extracting the date wrongly. Any clue why the ical standard is defined this way?

**Comment by Thalexander** [comment]
The range is defined to be exclusive of the end date ("The "DTEND" property for a "VEVENT" calendar component specifies the non-inclusive end of the event"), quite a few languages use an inclusive start exclusive end for slicing arrays too so it's not too unusual.

**Pull request merged**
