### PR TITLE
SourceDialog.vala: Add Mint and Bubblegum

### PR DESCRIPTION
**Pull request by 4jNsY6fCVqZv**
Supersedes elementary#538
Closes https://github.com/elementary/calendar/issues/529

### CODE REVIEW

**Review by fabiozaramella — APPROVED** [review]

**Comment by fabiozaramella** [comment]
@danrabbit Is there going to be a new release for Hera or can we proceed?

**Comment by danrabbit** [comment]
@fabiozaramella it seems like it would probably be worth doing another release since there was a fix for duplicate events in the sidebar after adding

**Comment by fabiozaramella** [comment]
@danrabbit great, I'm going to approve a couple more PRs but mark them as blocked for the moment, if that's not a problem. Waiting to merge them after a new release of Calendar.

**Review by danrabbit — APPROVED** [review]
Looks good, nice work!

**Pull request merged**
