### PR TITLE
Allow right clicking week labels

### PR DESCRIPTION
**Pull request by Thalexander**
Fixes right clicking week labels to allow hiding them.

### CODE REVIEW

**Comment by Thalexander** [comment]
Well it is easier to discover than right clicking the week days.

**Comment by jeremypw** [comment]
But the user would have already discovered that to show the week numbers (which are not shown by default)?

**Comment by Thalexander** [comment]
They're shown by default, org.pantheon.maya.settings.show-weeks has a default of true in the schema.

**Comment by jeremypw** [comment]
Ah, OK, my mistake, they've always been off for me.  Anyway, I have no objection, just noting elementaryos generally discourages too many alternatives ways of doing things.

**Pull request merged**
