### PR TITLE
Fix meson warning for run_command

### PR DESCRIPTION
**Pull request by turbobastii**
Since I am already fixing the other repos with this issue, I thought I might do it here aswell.

TLDR: meson will change the default behaviour of `run_command` and displays that as a warning when building.
See: https://github.com/mesonbuild/meson/issues/9300

image

### CODE REVIEW

**Comment by tintou** [comment]
Don't we want it to be true?

**Comment by turbobastii** [comment]
Well it was false implicitly by default, but if you think it would make more sense if it was true, I can of course change it.

**Comment by eli-schwartz** [comment]
> Well it was false implicitly by default

If the implicit default was generally good, then we (Meson) would not have deprecated it in the hope of eventually changing the default. :)

When adding an explicit value, it is wisest to consider what that value would be best served by being, rather than just explicating the default purely to quell the warning.

**Comment by turbobastii** [comment]
Very well put, thank you. I changed it accordingly.

**Review by lenemter — APPROVED** [review]

**Pull request merged**
