### PR TITLE
694: Replace deprecated function call. Add null check.

### PR DESCRIPTION
**Pull request by jpgleeson**
Update deprecated function call and gate behind null check. #694

### CODE REVIEW

**Comment by jeremypw** [comment]
The code appears to make sense but not sure how to check.  An existing event linked to my Google account did not show my Google avatar (just the fallback first letter one).

**Comment by jeremypw** [comment]
There is some extraneous white space at the end of line 111 causing lint failure.

**Comment by jpgleeson** [comment]
Linting fixed in 14acae1.

I believe it won't show the correct remote avatar until we set up a backend to fetch and store these avatars to the local machine similar to the Mail backend for Local and Gravatar. I've been tipping away at a PR for this but it won't be for some time.

**Review by jeremypw — APPROVED** [review]
LGTM -thanks!

**Pull request merged**
