### PR TITLE
Port to meson build system

### PR DESCRIPTION
**Pull request by tintou**
Because of future and stuff

### CODE REVIEW

**Comment by codygarver** [comment]
Found them, they're named `elementary-calendar.vapi` and `elementary-calendar.h` now instead of `io.elementary.calendar.*`

**Comment by tintou** [comment]
@codygarver Yeah, the issue here is that the pkg-config file was "libmaya-calendar", the .po file was libelementary-calendar and the headers were RDNN so let's stuck with libelementary-calendar everywhere.

**Comment by worldofpeace** [comment]
Doesn't this need a post_install script like [this](https://github.com/elementary/code/blob/master/meson/post_install.py)?

**Comment by worldofpeace** [comment]
I added it here #254

**Pull request merged**
