### PR TITLE
Show multi-day all day events correctly #137

### PR DESCRIPTION
**Pull request by Thalexander**
Similarly to #136 the interval being added can cause the agenda view to show the event on the wrong days

### CODE REVIEW

**Comment by jeremypw** [comment]
Please describe the bug being fixed more clearly with an example for testing.  When testing this PR, I was still getting incorrect date ranges for multi-day all-day events.  Used 2 day events in a European timezone, both within and across month boundaries (September/October).  In the right-hand panel (Today's events and Upcoming events) these events were shown as 3 day events, ending on the day following the correct one.

**Comment by matzipan** [comment]
This seems linked to bug report #137

**Comment by jeremypw** [comment]
If I have understood the bug correctly, this PR does not seem to fix it for me.

**Comment by matzipan** [comment]
@jeremypw to test this create an all-day event spanning multiple days and then in month view click on the last of the days that that event should span and in master, the agenda view will not show the event.

**Comment by jeremypw** [comment]
OK, I can confirm that this bug is solved.  It appears I was looking at a different, related bug that is not fixed.

**Pull request merged**
