### PR TITLE
Make the hex values consistent…

### PR DESCRIPTION
**Pull request by 4jNsY6fCVqZv**
…with the color constants of ColorButton.css

### CODE REVIEW

**Comment by danrabbit** [comment]
This is intentional since (for example) `#f9c440` is only 1.6:1 contrast against white and `#e6a92a` is 2.1:1

I'm inclined to close this since it would reduce contrast quite a bit

**Comment by 4jNsY6fCVqZv** [comment]
Currently, the color constants mentioned in ColorButton.css do not always correspond to the hex values of the corresponding places in the SourceDialog.vala.
Also, the SourceDialog.vala contains hex values that are not part of the official color palette.

My PR would like to adjust this in an intermediate step, so that I can take care of the WCAG compliance in a further step. See my comments on this in https://github.com/elementary/calendar/pull/530

So what do you think about merging this PR and then looking again specifically at the contrasts, if the use of hex values and color constants is at least consistent with the official color palette again?

**Comment by danrabbit** [comment]
Legibility here is more important to usability than consistency. Any changes need to continue to pass contrast checks

**Comment by 4jNsY6fCVqZv** [comment]
For comparison:

red
before: `#da3d41` -> 4,4:1 WCAG A
after: `#ed5353` -> 3,5:1 WCAG A

orange
before: `#f37329` -> 2,9:1
after: `#ffa154` -> 2,0:1

yellow
before: `#e6a92a` -> 2,1:1
after: `#f9c440` -> 1,6:1

green
before: `#81c837` -> 2,0:1
after: `#68B723` -> 2,5:1

Currently the ColorButton.css shows color constants that are not reflected by the hex values in the SourceDialog.vala.
Red, yellow and green use color values that are not part of the official color palette.

If I look at the comparison, by switching to the official green we could even slightly increase the contrast and by switching to the official red we would also retain the current WCAG compliance.

What scope for improvement do you see in terms of more consistency? At the moment it is simply not coherent in the code.

**Comment by 4jNsY6fCVqZv** [comment]
@danrabbit Can you look at it again?

**Comment by 4jNsY6fCVqZv** [comment]
For me this PR is directly connected to https://github.com/elementary/calendar/pull/562. If some colors are not supposed to correspond to the elementary color palette, I don't need to use the color name of the official palette for those, do I?

**Pull request closed without merging**
