### PR TITLE
Change accent color to lime

### PR DESCRIPTION
**Pull request by cassidyjames**
Pretty subtle, but carries the green calendar brand into the app more, which I think I like.

screenshot from 2018-10-19 16 29 44
screenshot from 2018-10-19 16 30 19

### CODE REVIEW

**Comment by lainsce** [comment]
Don't forget current day selection, it's still blue :P

**Comment by cassidyjames** [comment]
Using the accent variable gives me this, which I wasn't as hot on

image

**Comment by lainsce** [comment]
Looks nice to me, to be honest

**Comment by danrabbit** [comment]
Hm something is awry here. I'm not seeing the accent color on switches etc, only for the selected day

**Comment by cassidyjames** [comment]
@danrabbit ah yeah interesting. The same definition works in the inspector but not here. I'm guessing it's however the CSS is being loaded?

**Comment by cassidyjames** [comment]
@danrabbit since this is an app-wide change and not just for the calendar view, I added a new Application stylesheet and loaded it for the app.

**Comment by cassidyjames** [comment]
screenshot from 2018-12-12 16 42 31
screenshot from 2018-12-12 16 42 37
screenshot from 2018-12-12 16 43 00

**Pull request merged**
