### PR TITLE
AgendaEventRow: Search OpenStreetMap for locations

### PR DESCRIPTION
**Pull request by danrabbit**
iOS calendar adds `\n` for all location strings, so we can easily get just the address by looking for this and splitting there. If there's no split, we just search for the whole string.

### CODE REVIEW

**Comment by cassidyjames** [comment]
Works sometimes on my events. One thing I noticed is that it looks like we're not URL encoding the strings.

**Comment by jeremypw** [comment]
This works pretty well for me with events created in elementary calendar at least.  However, there is no tooltip when hovering over the location text indicating what will happen if you click on it (and the text is not underlined or otherwise indicating that it is a hyperlink to a map).

**Comment by cassidyjames** [comment]
@jeremypw no it should probably be more obviously a link without requiring mystery-meat hovering around.

**Comment by jeremypw** [comment]
@danrabbit Converting to draft as has uaddressed issues and no recent activity.  Please feel free to close or reopen for review after fixing conflicts as desired.

**Comment by danrabbit** [comment]
Yeah this is kind of doo doo, closing

**Pull request closed without merging**
